Подключает Redux к проекту, добавляет привязку компонента main-screen…
htmlacademy-react/167715-six-cities-6 pull request #7
Opened 2021-03-21 23:32 UTC by Zarin417

… к store

2021-03-22 09:46 UTC, AleksandrLv requested changes

2021-03-22 09:46 UTC, AleksandrLv commented on src/index.js
> +      <App offers={offers} reviews ={reviews} />
Пробел перед =

2021-03-22 09:46 UTC, AleksandrLv commented on src/store/reducer.js
> +  currentCity: `Paris`,
Обратные кавычки здесь не нужны

2021-03-22 09:46 UTC, AleksandrLv commented on src/components/main-screen/main-screen.jsx
> +export {MainScreen};
export лишний

2021-03-22 09:46 UTC, AleksandrLv commented on src/components/main-screen/main-screen.jsx
> +                      <use xlinkHref="#icon-arrow-select"/>
Нужен пробел перед `/>`

2021-03-22 09:46 UTC, AleksandrLv commented on src/components/main-screen/main-screen.jsx
> +            ? <div className="cities__places-container container">
Сложно читается такой вид записи тернарного оператора.
Визуально будет лучше такой вариант
```jsx
{offers.length !== 0 ? (
    <div />
) : (
    <div />
)}
```

2021-03-22 09:46 UTC, AleksandrLv commented on src/components/main-screen/main-screen.jsx
> +          : `page__main page__main--index page__main--index-empty`
Повторяющиеся классы усложняют код. Лучше условие ставить только на то, что отличается. 
```jsx
className={`page__main page__main--index${offers.length === 0 && 'page__main--index-empty'}`}
```

Если `&&` не сработает, то тернарный `offers.length === 0 ? 'page__main--index-empty' : ''`

2021-03-22 09:46 UTC, AleksandrLv commented on src/components/main-screen/main-screen.jsx
> +          : `page__main page__main--index page__main--index-empty`
Повторяющиеся классы усложняют код. Лучше условие ставить только на то, что отличается. 
```jsx
className={`page__main page__main--index${offers.length === 0 && 'page__main--index-empty'}`}
```

Если `&&` не сработает, то тернарный `offers.length === 0 ? 'page__main--index-empty' : ''`

2021-03-22 09:46 UTC, AleksandrLv commented on src/components/cities-list/cities-list.jsx
> +                : `locations__item-link tabs__item`
Тут такая же история

2021-03-22 09:46 UTC, AleksandrLv commented on src/components/cities-list/cities-list.jsx
> +    onChangeCity(evt.target.innerText);
Опасненько из разметки брать текст и его использовать. Например, к городу дизайнеры что-то захотят добавить (эмоджи) и тогда уже innerText невозможно будет использовать как сейчас. Или опечатку в разметке сделаешь, например, пробел и функционал перестанет работать.

Предлагаю сделать компонент, где будет рендериться только один город и в него передавать `city`, который и будешь использовать для функции `onChangeCity`

2021-03-22 13:51 UTC, Zarin417 commented on src/index.js
> +      <App offers={offers} reviews ={reviews} />
done

2021-03-22 13:55 UTC, Zarin417 commented on src/store/reducer.js
> +  currentCity: `Paris`,
done

2021-03-22 13:56 UTC, Zarin417 commented on src/components/main-screen/main-screen.jsx
> +export {MainScreen};
Это экспорт на перспективу для тестирования (Сушко рекомендовал)

2021-03-22 13:58 UTC, Zarin417 commented on src/components/main-screen/main-screen.jsx
> +                      <use xlinkHref="#icon-arrow-select"/>
done

2021-03-22 14:20 UTC, Zarin417 commented on src/components/cities-list/cities-list.jsx
> +                : `locations__item-link tabs__item`
done

2021-03-22 14:20 UTC, Zarin417 commented on src/components/main-screen/main-screen.jsx
> +          : `page__main page__main--index page__main--index-empty`
done

2021-03-22 14:20 UTC, Zarin417 commented on src/components/main-screen/main-screen.jsx
> +          : `page__main page__main--index page__main--index-empty`
done

2021-03-22 14:35 UTC, Zarin417 commented on src/components/main-screen/main-screen.jsx
> +            ? <div className="cities__places-container container">
done

2021-03-22 15:23 UTC, AleksandrLv commented on src/components/cities-list/cities-list.jsx
> +                : `locations__item-link tabs__item`
```jsx
<City city={city} isActive={currentCity === city} onClick={handleCityClick} />
```

2021-03-22 15:25 UTC, AleksandrLv commented on src/components/cities-list/cities-list.jsx
> +    onChangeCity(evt.target.innerText);
```jsx
<City city={city} isActive={currentCity === city} onClick={handleCityClick} />
```

2021-03-22 23:38 UTC, AleksandrLv requested changes

2021-03-22 23:38 UTC, AleksandrLv commented on src/components/city/city.jsx
> +    <li key={city} className="locations__item">
key здесь не нужен

2021-03-22 23:38 UTC, AleksandrLv commented on src/components/main-screen/main-screen.jsx
> +                  Popular
Сдвинуть вправо надо

2021-03-22 23:38 UTC, AleksandrLv commented on src/components/main-screen/main-screen.jsx
>            }
`)}` Можно так делать. Линтеры(автоматическая проверка кода) обычно так настроены

2021-03-22 23:38 UTC, AleksandrLv commented on src/store/reducer.js
> +  currentCity: CITIES[0],
👍

2021-03-23 11:25 UTC, Zarin417 commented on src/components/city/city.jsx
> +    <li key={city} className="locations__item">
done

2021-03-23 11:26 UTC, Zarin417 commented on src/components/main-screen/main-screen.jsx
> +                  Popular
done

2021-03-23 11:27 UTC, Zarin417 commented on src/components/main-screen/main-screen.jsx
>            }
done

2021-03-23 11:30 UTC, Zarin417 commented on src/store/reducer.js
> +  currentCity: CITIES[0],
я так понимаю done ))

2021-03-23 12:12 UTC, merged